### ISSUE TITLE
Chart.lock is out of sync

### ISSUE THREAD

**Issue by outbackdingo** [mum-project/k8s-helm-charts#3]
Error: Chart.lock is out of sync with Chart.yaml

**Comment by martbock** [comment]
The chart in this repository was based on Helm 2, where dependencies were declared in the files `requirements.yaml` and `requirements.lock`.
With Helm 3, the dependencies have been consolidated into the `Chart.yaml` and `Chart.lock` files.

See: https://helm.sh/docs/faq/#consolidation-of-requirementsyaml-into-chartyaml

I have pushed the necessary change with 064e2a731a711d0c4a5585cddd7179a84ff4495f.
Next time, please create a pull request or at least do more than pasting your error message into a new GitHub issue.
